name: Zaproxy Scan

on:
  push:
    branches: [ "main", "dapclarke-actiondemo-1" ]
  pull_request:
    branches: [ "main", "dapclarke-actiondemo-1" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication

    permissions:
      actions: write
      #contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: 'https://testrestapi-gcefhdbrgdddced4.uksouth-01.azurewebsites.net/greeting'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

#REFs:
# https://github.com/marketplace/actions/zap-api-scan